# Generated by Django 2.2.1 on 2019-06-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseList',
        ),
    ]
