# Generated by Django 2.2.1 on 2019-07-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20190710_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='date_begin',
        ),
    ]
