# Generated by Django 2.2.1 on 2019-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_remove_courselist_date_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='date_begin',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
