# Generated by Django 2.2.1 on 2019-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_remessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='remessage',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
