# Generated by Django 2.2.1 on 2019-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
