# Generated by Django 2.2.1 on 2019-08-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_account_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
