# Generated by Django 2.2.1 on 2019-08-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0018_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='user_id',
        ),
    ]
