# Generated by Django 2.2.1 on 2019-08-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0020_auto_20190827_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
