# Generated by Django 2.2.5 on 2019-09-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0025_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('course_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursepage', to='snippets.CoursePage')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercourse', to='snippets.CourseUsers')),
            ],
        ),
    ]
