# Generated by Django 2.2.5 on 2019-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0026_gradelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeList',
        ),
    ]
