# Generated by Django 2.2.5 on 2019-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0028_gradelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelist',
            name='owner_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
